- name: Install and run CRITS
  hosts: all
  tasks:
    - name: install epel
      yum: name=epel-release state=present

    - name: install pip
      yum: name=python-pip state=present

    - name: install docker-py
      pip:
        name: "{{ item }}"
      with_items:
      - docker-py

    - name: get crits image
      docker_image:
        name: remnux/crits
        state: present

    - name: create crits data directory
      file: path=~/crits-data state=directory

    - name: run crits
      docker_container:
        name: crits
        state: started
        restart: yes
        image: remnux/crits
        published_ports: 8443:8443
        volumes:
          - ~/crits-data:/home/nonroot/workdir

