- name: install docker-py
  pip:
    name: "{{ item }}"
    with_items:
    - docker-py

- name: get crits image
  docker_image:
    name: remnux/crits
    state: present

- name: run crits
  docker_container:
    name: crits
    state: started
    restart: yes
    image: remnux/crits
    published_ports: 80:80

